# Generated by Django 5.1.7 on 2025-09-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="cons",
        ),
        migrations.RemoveField(
            model_name="review",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="pros",
        ),
        migrations.RemoveField(
            model_name="review",
            name="visibility",
        ),
    ]
