# Generated by Django 5.1.7 on 2025-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_remove_review_cons_remove_review_dislikes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="cons",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="pros",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("friends", "Shared with Friends"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
