# Generated by Django 5.1.7 on 2025-09-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "journal",
            "0003_review_cons_review_dislikes_review_likes_review_pros_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="cons",
        ),
        migrations.RemoveField(
            model_name="review",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="pros",
        ),
    ]
