# Generated by Django 5.1.7 on 2025-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0004_alter_profile_photo_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
